# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('account', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=40)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('patient', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.Patients')),
                ('sitting', models.FloatField(default=0.0)),
                ('standing', models.FloatField(default=0.0)),
                ('walking', models.FloatField(default=0.0)),
                ('running', models.FloatField(default=0.0)),
            ],
        ),
    ]
