# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='patients.Patients')),
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(primary_key=True)),
                ('end_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='account',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
