# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='patient',
            new_name='account',
        ),
    ]
