# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20171123_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lyingDown',
            field=models.FloatField(default=0.0),
        ),
    ]
