# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_activity_lyingdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.Patients')),
                ('running', models.FloatField(default=0.0)),
                ('sitting', models.FloatField(default=0.0)),
                ('standing', models.FloatField(default=0.0)),
                ('walking', models.FloatField(default=0.0)),
                ('lyingDown', models.FloatField(default=0.0)),
            ],
        ),
    ]
